version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/golang:1.12
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - restore_cache:
        keys:
          - v1-pkg-cache
      - run: 
          name: Run unit tests
          command: go test ./... -cover=$TEST_RESULTS
      - run:
          name: Build
          command: go build ./...
      - save_cache:
        paths:
          - "/go/pkg"
        key: v1-pkg-cache
      - store_test_results:
        path: /tmp/test-results
workflows:
  version: 2
  build_test:
    jobs:
      - build_test